# Copyright 2026 Terradue
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-08-05T11:06:48+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class Exception(BaseModel):
    """
    Information about the exception: an error code plus an optional description.
    """

    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    code: str
    description: str | None = None
